image: jekyll/builder

variables:
  JEKYLL_ENV: production
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"

cache:
  paths:
  - vendor/

before_script:
  - bundle install --path vendor
  - wget -O _data/events/eventlist.csv https://docs.google.com/spreadsheets/d/$EVENTSHEET/gviz/tq?tqx=out:csv\&sheet=Events
  - wget -O _data/events/bidlist.csv https://docs.google.com/spreadsheets/d/$EVENTSHEET/gviz/tq?tqx=out:csv\&sheet=Bidlist
  - wget -O _data/groups/grouplist.csv https://docs.google.com/spreadsheets/d/$GROUPSHEET/gviz/tq?tqx=out:csv\&sheet=groups
  - wget -O _data/groups/officerlist.csv https://docs.google.com/spreadsheets/d/$GROUPSHEET/gviz/tq?tqx=out:csv\&sheet=officers

pages:
  environment: staging
  script:
  - bundle exec jekyll build -d public/j
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
  - staging

deploy:
  environment: production
  script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
  - bundle exec jekyll build -d public/j
  - rsync -rvzc -e 'ssh -p 2222' public/j $WEBHOST:public_html/
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  only:
  - master