name: My workflow
on: 
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: bundle install
    - run: pwd
    - run: ls
    - name: Fetch external data
      shell: bash
      env:
        GOOGLE_SERVICE_PRIVATE_KEY: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
        GOOGLE_SERVICE_PRIVATE_KEY_ID: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY_ID }}
        HELLO_WORLD: 'hello i am here'
      run: ./_build.sh
    - name: Build site
      run: LC_ALL="C.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" bundle exec jekyll build
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: html
        path: _site
        retention-days: 1
