name: Build and upload staging site
on: 
  push:
    branches: [staging]
  workflow_dispatch:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: env
